repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.10
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.6
    hooks:
      - id: uv-lock
  - repo: https://github.com/checkmake/checkmake.git
    rev: 0.2.2
    hooks:
      - id: checkmake
  - repo: local
    hooks:
      - id: lint-viewer
        name: lint-viewer
        entry: bash -c 'cd viewer && npm run lint'
        language: system
        pass_filenames: false
